version: '3.8'

name: gen-ai-stack

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  db:
    image: pgvector/pgvector:pg17
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: gen-ai # Replace with your desired password
    ports:
      - "8082:5432"
    volumes:
      - ../../pgdata:/var/lib/postgresql/data # Replace with your desired volume location

volumes:
  pgdata:

