version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: gen-ai # Replace with your desired password
    ports:
      - "8082:5432"
    volumes:
      - ../../pgdata:/var/lib/postgresql/data # Replace with your desired volume location

volumes:
  pgdata:
